### PR TITLE
open source: what it means to me

### PR DESCRIPTION
**Pull request by LeonardoCardoso**

### CODE REVIEW

**Comment by justinclift** [comment]
Thanks @LeonardoCardoso, that's pretty cool. :smile:

**Comment by LeonardoCardoso** [comment]
Haha! 😂

On Friday, April 24, 2015, Justin Clift <notifications@github.com> wrote:

> Thanks @LeonardoCardoso <https://github.com/LeonardoCardoso>, that's
> pretty cool. [image: :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nickdesaulniers/What-Open-Source-Means-To-Me/pull/84#issuecomment-95962374>
> .
>


-- 
*Leonardo Cardoso*
leocardz.com

<http://git.io/vfgvV>

**Comment by nickdesaulniers** [comment]
Open source as a form of altruism, I like it.  Obrigado Leonardo!  [Maybe you can help us find more contributors](https://github.com/nickdesaulniers/What-Open-Source-Means-To-Me/issues/20)?

**Comment by LeonardoCardoso** [comment]
Yes. I see it like that. I will find more contributors.

**Pull request merged**
