### PR TITLE
Open source means to me... @gioyik

### PR DESCRIPTION
**Pull request by Gioyik**

### CODE REVIEW

**Comment by justinclift** [comment]
Are these typos?

* "style life" &rarr; "life style"
* "other life's too" &rarr; "other lives too"
* "you can stop" &rarr; "you can't stop"   &larr; I'm not sure about this one :wink:
* "that thrust on open source too" &larr; I'm not understanding this bit. :innocent:

**Comment by nickdesaulniers** [comment]
"I starts to be a feeling" --> "It starts to be a feeling"

**Comment by Gioyik** [comment]
Hi, Thanks for the corrections, I really appreciate it. I did the changes, so let me know if there's something else to change.

**Comment by nickdesaulniers** [comment]
Hey Giovanny, thanks for PR!  I appreciate it.  Let me know if reps ever sends you up to California, or I'll let you know next time I'm in Colombia!

**Comment by nickdesaulniers** [comment]
Maybe you could help us get [more contributors](https://github.com/nickdesaulniers/What-Open-Source-Means-To-Me/issues/20)?  Would love to have more contributions in Spanish!

**Comment by Gioyik** [comment]
@nickdesaulniers thanks for merge my changes, I really love the idea in this repository. I will CC more people that will be glad to add opinions here. Thank you.

Let me know if you visit Colombia, I will be glad to see you here. Maybe someday I will have the opportunity to visit California and be sure I will let you know it.

Thank you

**Pull request merged**
